// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package store

import (
	"context"
)

const countItems = `-- name: CountItems :one
SELECT count(*) FROM items
`

func (q *Queries) CountItems(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countItems)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createItem = `-- name: CreateItem :one
INSERT INTO items (title)
VALUES ($1)
RETURNING id, title, created_at
`

func (q *Queries) CreateItem(ctx context.Context, title string) (Item, error) {
	row := q.db.QueryRow(ctx, createItem, title)
	var i Item
	err := row.Scan(&i.ID, &i.Title, &i.CreatedAt)
	return i, err
}

const deleteItem = `-- name: DeleteItem :exec
DELETE FROM items
WHERE id = $1
`

func (q *Queries) DeleteItem(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteItem, id)
	return err
}

const listItems = `-- name: ListItems :many

SELECT id, title, created_at
FROM items
ORDER BY created_at DESC, id DESC
LIMIT $1
`

// Queries for the example feature. sqlc generates type-safe, parameterized Go
// from these into ./store. Never build SQL with string concatenation.
func (q *Queries) ListItems(ctx context.Context, limit int32) ([]Item, error) {
	rows, err := q.db.Query(ctx, listItems, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Item{}
	for rows.Next() {
		var i Item
		if err := rows.Scan(&i.ID, &i.Title, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
