// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"
)

type Querier interface {
	CountItems(ctx context.Context) (int64, error)
	CreateItem(ctx context.Context, title string) (Item, error)
	DeleteItem(ctx context.Context, id int64) error
	// Queries for the example feature. sqlc generates type-safe, parameterized Go
	// from these into ./store. Never build SQL with string concatenation.
	ListItems(ctx context.Context, limit int32) ([]Item, error)
}

var _ Querier = (*Queries)(nil)
