// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"time"
)

type Item struct {
	ID        int64
	Title     string
	CreatedAt time.Time
}

type Session struct {
	TokenHash []byte
	UserID    int64
	ExpiresAt time.Time
	CreatedAt time.Time
}

type User struct {
	ID           int64
	Email        string
	PasswordHash string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
