// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"
)

type Querier interface {
	CreateSession(ctx context.Context, arg CreateSessionParams) error
	// Queries for the auth feature. sqlc generates type-safe, parameterized Go into
	// ./store. Emails are lowercased by the handler before they reach these queries.
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteExpiredSessions(ctx context.Context) error
	DeleteSession(ctx context.Context, tokenHash []byte) error
	// Validates the session and returns its user in one round trip, filtering
	// expired rows in SQL so the handler never honors a stale session.
	GetSessionUser(ctx context.Context, tokenHash []byte) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
}

var _ Querier = (*Queries)(nil)
